// Test generated by RoostGPT for test zb-test using AI Type Open AI and AI Model gpt-4

package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

type test struct {
	method string
	body   string
	want   int
}

func TestServeRoot(t *testing.T) {
	tests := []test{
		{method: "GET", want: http.StatusOK},
		{method: "POST", body: `{"VoterID":"voter1","CandidateID":"candidate1"}`, want: http.StatusCreated},
		{method: "POST", body: `{"VoterID":"voter1"}`, want: http.StatusBadRequest},
		{method: "PUT", want: http.StatusMethodNotAllowed},
	}

	for _, tc := range tests {
		req, err := http.NewRequest(tc.method, "/", strings.NewReader(tc.body))
		if err != nil {
			t.Fatal(err)
		}

		rr := httptest.NewRecorder()
		handler := http.HandlerFunc(serveRoot)

		handler.ServeHTTP(rr, req)

		if status := rr.Code; status != tc.want {
			t.Errorf("handler returned wrong status code: got %v want %v",
				status, tc.want)
		}
	}
}
